require("dotenv").config();
const fs = require("fs/promises");
const path = require("path");
const pool = require("./pool");
const { buildOperationalBackup } = require("../controllers/report.controller");

const defaultBackupDir = path.join(__dirname, "..", "..", "backups");
const defaultRetentionDays = 180;

const timestamp = () => new Date().toISOString().replace(/[:.]/g, "-");

const getArgValue = (name, fallback = "") => {
  const prefix = `--${name}=`;
  const match = process.argv.find((arg) => arg.startsWith(prefix));
  return match ? match.slice(prefix.length) : fallback;
};

const backupDir = () => path.resolve(getArgValue("dir", process.env.BACKUP_DIR || defaultBackupDir));
const retentionDays = () => Number(getArgValue("retention-days", process.env.BACKUP_RETENTION_DAYS || defaultRetentionDays));

const backupFileName = () => `agua-global-operational-backup-${timestamp()}.json`;

const createBackup = async () => {
  const dir = backupDir();
  await fs.mkdir(dir, { recursive: true });
  const backup = await buildOperationalBackup();
  const payload = {
    export_type: "operational_backup",
    exported_at: new Date().toISOString(),
    exported_by: {
      source: "server-script",
      command: "npm run db:backup"
    },
    notes: [
      "Operational backup export generated by local script.",
      "Password hashes, reset tokens, and environment secrets are intentionally excluded.",
      "Knowledge document files are included as base64 and must be stored securely."
    ],
    retention_policy: {
      daily: "30 days",
      weekly: "12 weeks",
      monthly: "24 months",
      local_script_retention_days: retentionDays()
    },
    dataset_counts: backup.counts,
    skipped_datasets: backup.skipped,
    datasets: backup.datasets
  };
  const filePath = path.join(dir, backupFileName());
  await fs.writeFile(filePath, JSON.stringify(payload, null, 2), { flag: "wx" });
  return { filePath, datasetCount: Object.keys(backup.counts).length };
};

const pruneBackups = async () => {
  const dir = backupDir();
  const keepDays = retentionDays();
  if (!Number.isFinite(keepDays) || keepDays <= 0) {
    return { removed: [], keepDays };
  }

  await fs.mkdir(dir, { recursive: true });
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const cutoff = Date.now() - keepDays * 24 * 60 * 60 * 1000;
  const removed = [];

  for (const entry of entries) {
    if (!entry.isFile() || !/^agua-global-operational-backup-.*\.json$/.test(entry.name)) continue;
    const filePath = path.join(dir, entry.name);
    const stat = await fs.stat(filePath);
    if (stat.mtimeMs >= cutoff) continue;
    await fs.unlink(filePath);
    removed.push(filePath);
  }

  return { removed, keepDays };
};

const run = async () => {
  const command = process.argv[2] || "create";
  if (!["create", "prune", "monthly"].includes(command)) {
    throw new Error("Usage: node src/db/backup.js [create|prune|monthly] [--dir=backups] [--retention-days=180]");
  }

  if (command === "create") {
    const result = await createBackup();
    console.log(`Backup created: ${result.filePath}`);
    console.log(`Datasets exported: ${result.datasetCount}`);
    return;
  }

  if (command === "prune") {
    const result = await pruneBackups();
    console.log(`Retention: ${result.keepDays} day(s)`);
    console.log(`Backups removed: ${result.removed.length}`);
    return;
  }

  const backupResult = await createBackup();
  const pruneResult = await pruneBackups();
  console.log(`Monthly backup created: ${backupResult.filePath}`);
  console.log(`Datasets exported: ${backupResult.datasetCount}`);
  console.log(`Retention: ${pruneResult.keepDays} day(s)`);
  console.log(`Backups removed: ${pruneResult.removed.length}`);
};

run()
  .catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  })
  .finally(async () => {
    await pool.end();
  });
