import { EmptyTableRow } from "./EmptyState";
import { assetUrl } from "../services/api";

const money = (value) => `KES ${Number(value || 0).toLocaleString()}`;
const number = (value) => Number(value || 0).toLocaleString();
const optionalNumber = (value) => value === null || value === undefined || value === "" ? "-" : Number(value || 0).toLocaleString();
const dateOnly = (value) => value?.slice(0, 10) || "";
const dateTime = (value) => (value ? new Date(value).toLocaleString() : "");
const electricityCostSourceLabel = (week) => {
  if (week.electricity_cost_source === "period_topups") return "This period's top-ups";
  if (week.electricity_cost_source === "last_topup") return `Last top-up${week.electricity_cost_source_date ? ` on ${week.electricity_cost_source_date.slice(0, 10)}` : ""}`;
  return "No top-up cost available";
};
const weekTotals = (week) => ({ consumption: (week.rows || []).reduce((sum, row) => sum + Number(row.consumption || 0), 0), revenue: (week.rows || []).reduce((sum, row) => sum + Number(row.revenue_amount || 0), 0) });

export default function ProductionReportPrintSurface({ businessSettings, meterTypeLabels, printGeneratedAt, printMode, reportPeriodLabel, reportTotals, selectedMeter, visibleWeeks }) {
  const hasRows = visibleWeeks.length && (!selectedMeter || reportTotals.meterRowCount);
  const noData = <EmptyTableRow colSpan={6} title="No production report data" detail="Save weekly readings or adjust the meter filter." />;
  return <section className="panel print-surface report-print active-print-surface production-report-print">
    <div className="report-print-header">
      {businessSettings?.logo_url ? <img className="receipt-logo" src={assetUrl(businessSettings.logo_url)} alt="Business logo" /> : <div className="receipt-logo-mark">{businessSettings?.business_name?.slice(0, 2) || "AG"}</div>}
      <div><h3>{businessSettings?.business_name || "Water Billing"}</h3>{businessSettings?.legal_name ? <p>{businessSettings.legal_name}</p> : null}{businessSettings?.physical_address ? <p>{businessSettings.physical_address}</p> : null}<p>{[businessSettings?.phone, businessSettings?.email].filter(Boolean).join(" | ")}</p>{businessSettings?.tax_pin ? <p>PIN: {businessSettings.tax_pin}</p> : null}</div>
      <div className="report-print-meta"><span>Report</span><strong>{printMode === "summary" ? "Production Weekly Summary" : "Production Report"}</strong><small>{reportPeriodLabel}</small>{selectedMeter ? <small>{selectedMeter.label}</small> : null}<small>{printGeneratedAt ? `Generated ${dateTime(printGeneratedAt)}` : ""}</small></div>
    </div>
    <div className="reading-context"><div><span>Total consumption</span><strong>{number(reportTotals.consumption)}</strong></div><div><span>Total revenue</span><strong>{money(reportTotals.revenue)}</strong></div>{selectedMeter ? <div><span>Selected meter</span><strong>{selectedMeter.label}</strong><small>{reportTotals.meterRowCount} row(s)</small></div> : <><div><span>Electricity used</span><strong>{number(reportTotals.electricityUsed)} kWh</strong></div><div><span>Electricity cost</span><strong>{money(reportTotals.electricityCost)}</strong></div><div><span>Production cost</span><strong>{(Number(reportTotals.costOfProductionRatio || 0) * 100).toFixed(2)}%</strong></div><div><span>Cost / water unit</span><strong>{money(reportTotals.costPerWaterUnit)}</strong></div></>}</div>
    {printMode === "summary" ? <div className="table-wrap"><table><thead><tr><th>Week</th><th>kWh Used</th><th>Electricity Cost</th><th>Cost basis</th><th>Meter</th><th>Consumption</th><th>Revenue</th></tr></thead><tbody>{hasRows ? visibleWeeks.filter((week) => !selectedMeter || week.rows.length).map((week) => { const totals = weekTotals(week); return <tr className="production-week-summary" key={`print-week-${week.id}`}><td>{dateOnly(week.reading_date)}</td><td>{selectedMeter ? "-" : `${number(week.electricity_used)} kWh`}</td><td>{selectedMeter ? "-" : money(week.electricity_cost_used)}</td><td>{selectedMeter ? "Meter filter" : `${money(week.electricity_cost_per_unit)} / kWh`}<small>{selectedMeter ? selectedMeter.label : electricityCostSourceLabel(week)}</small></td><td>{selectedMeter ? selectedMeter.label : "Week total"}</td><td>{number(totals.consumption)}</td><td>{money(totals.revenue)}</td></tr>; }) : <EmptyTableRow colSpan={7} title="No production report data" detail="Save weekly readings or adjust the meter filter." />}</tbody></table></div> : <div className="production-print-week-list">{hasRows ? visibleWeeks.filter((week) => !selectedMeter || week.rows.length).map((week) => { const totals = weekTotals(week); return <div className="production-print-week" key={`full-print-week-${week.id}`}><div className="table-wrap"><table className="production-week-summary-table"><thead><tr><th>Week</th><th>kWh Used</th><th>Electricity Cost</th><th>Cost basis</th><th>Consumption</th><th>Revenue</th></tr></thead><tbody><tr className="production-week-summary"><td>{dateOnly(week.reading_date)}</td><td>{selectedMeter ? "-" : `${number(week.electricity_used)} kWh`}</td><td>{selectedMeter ? "-" : money(week.electricity_cost_used)}</td><td>{selectedMeter ? "Meter filter" : `${money(week.electricity_cost_per_unit)} / kWh`}<small>{selectedMeter ? selectedMeter.label : electricityCostSourceLabel(week)}</small></td><td>{number(totals.consumption)}</td><td>{money(totals.revenue)}</td></tr></tbody></table></div><div className="table-wrap"><table className="production-meter-detail-table"><thead><tr><th>Week</th><th>Meter</th><th>Previous</th><th>Current</th><th>Consumption</th><th>Revenue</th></tr></thead><tbody>{week.rows.map((row) => <tr key={`print-${week.id}-${row.id}`}><td>{dateOnly(week.reading_date)}</td><td>{row.meter_number}<small>{row.customer_name || row.meter_name || meterTypeLabels[row.meter_type]}</small></td><td>{optionalNumber(row.previous_reading_value)}</td><td>{optionalNumber(row.reading_value)}</td><td>{number(row.consumption)}</td><td>{money(row.revenue_amount)}</td></tr>)}</tbody></table></div></div>; }) : <div className="table-wrap"><table><tbody>{noData}</tbody></table></div>}</div>}
    <div className="report-print-footer">{businessSettings?.report_footer_note ? <p>{businessSettings.report_footer_note}</p> : null}<small>{businessSettings?.business_name || "Water Billing"} {printMode === "summary" ? "production weekly summary" : "production report"} | {reportPeriodLabel}</small></div>
  </section>;
}
